---
-  name: manage web servers
   hosts: web_servers
   remote_user: root
   tasks:
    - name: install nginx package
      yum: name=nginx state=present
    - name: copy nginx.conf to remote server
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    - name: start nginx server
      service:
        name: nginx
        enabled: true
        state: started
-  name: manage db servers
   hosts: db_servers
   tasks:
    - name: update database conf
      copy: src=my.cnf dest=/etc/my.cnf
...
