# Print Facts variables
---
-  name: print facts variables
   hosts: all
   remote_user: ubuntu
   tasks:
    - name: install nginx package
      yum: name=nginx state=present
    - name: copy nginx.conf to remote server
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    - name: start nginx server
      service:
        name: nginx
        state: started
...