# Close Facts gathering
---
-  name: a playbook example
   hosts: web
   gather_facts: no
   remote_user: ubuntu
   tasks:
    - name: install nginx package
      apt: name=nginx state=present
    - name: copy nginx.conf to remote server
      copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    - name: start nginx server
      service:
        name: nginx
        state: started
...
